Repository The-Undefined-Santex/The_Undefined, pull requests merged in 2023-09, with the labels that each got.

#7 style(readme): Update the readme file
  pull_request_template.md
Labels: documentation

#9 feat(frontend): Add a new feature for merge into dev
  front/src/app/components/banner/banner.component.html
  front/src/app/components/banner/banner.component.scss
  front/src/app/components/companies/companies.component.html
  front/src/app/components/companies/companies.component.scss
  front/src/app/components/components.module.ts
  front/src/app/components/courses/all-courses/all-courses.component.html
  front/src/app/components/courses/all-courses/all-courses.component.scss
  front/src/app/components/courses/all-courses/all-courses.component.ts
  front/src/app/components/courses/landing-courses/landing-courses.component.html
  front/src/app/components/footer/footer.component.scss
  front/src/app/components/header/header.component.html
  front/src/app/components/header/header.component.scss
  front/src/app/components/home/home.component.html
  front/src/app/components/pipes/filter.pipe.spec.ts
  front/src/app/components/pipes/filter.pipe.ts
  front/src/app/components/pipes/result.pipe.spec.ts
  front/src/app/components/pipes/result.pipe.ts
  front/src/assets/banner.jpg
Labels: bug, feature, optimization

#10 chore: Remove courses-details service
  front/src/app/services/courses-details.service.spec.ts
  front/src/app/services/courses-details.service.ts
Labels: optimization

#11 feat: Feature/form inscr courses
  front/src/app/app-routing.module.ts
  front/src/app/components/courses/courses-detail/courses-detail.component.html
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.html
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.scss
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.ts
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.html
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.ts
  front/src/app/components/pay-transf-course.module.ts
  front/src/app/lib/primeNG/primeng/primeng.module.ts
Labels: feature

#12 feat: Update the routing module
  front/src/app/app-routing.module.ts
  front/src/app/components/courses/all-courses/all-courses.component.html
  front/src/app/components/courses/landing-courses/landing-courses.component.html
Labels: feature

#15 feat: Feature/form inscr courses
  front/src/app/app-routing.module.ts
  front/src/app/app.module.ts
  front/src/app/components/courses-mockSuccess-routing.module.ts
  front/src/app/components/courses-mockUnseccesfully-routing.module.ts
  front/src/app/components/courses/courses-detail/courses-detail.component.html
  front/src/app/components/courses/courses-mock/mock-success.component.html
  front/src/app/components/courses/courses-mock/mock-success.component.scss
  front/src/app/components/courses/courses-mock/mock-success.component.spec.ts
  front/src/app/components/courses/courses-mock/mock-success.component.ts
  front/src/app/components/courses/courses-mock/mock-unsuccessfully.component.html
  front/src/app/components/courses/courses-mock/mock-unsuccessfully.component.scss
  front/src/app/components/courses/courses-mock/mock-unsuccessfully.component.spec.ts
  front/src/app/components/courses/courses-mock/mock-unsuccessfully.component.ts
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.html
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.html
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.ts
  front/src/app/components/pay-transf-course-routing.module.ts
  front/tsconfig.json
Labels: feature

#16 refactor: Refactor the EndDate method
  front/src/app/components/courses/courses-detail/courses-detail.component.html
  front/src/app/services/courses.service.ts
Labels: optimization

#18 Ludmila
  front/src/app/app-routing.module.ts
  front/src/app/app.module.ts
  front/src/app/components/courses/all-courses/all-courses.component.html
  front/src/app/components/courses/all-courses/all-courses.component.scss
  front/src/app/components/courses/landing-courses/landing-courses.scss
  front/src/app/components/error404/error404.component.html
  front/src/app/components/error404/error404.component.scss
  front/src/app/components/error404/error404.component.spec.ts
  front/src/app/components/error404/error404.component.ts
  front/src/app/components/header/header.component.scss
  front/src/app/components/testimonials/testimonials.component.scss
Labels: feature

#21 feat: Add a contact form feature
  front/package.json
  front/src/app/components/contact/contact.component.html
  front/src/app/components/contact/contact.component.scss
  front/src/app/components/contact/contact.component.ts
  front/src/app/components/home/home.component.html
Labels: feature

#20 Feature/form inscr courses
  front/src/app/components/courses/courses-mock/mock-unsuccessfully.component.html
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.html
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.scss
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.ts
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.html
  front/src/app/components/courses/pay-transf-course/pay-transf-course.component.ts
Labels: bug

#26 feature: Add user login
  front/src/app/components/courses/all-courses/all-courses.component.ts
  front/src/app/components/courses/courses-detail/courses-detail.component.ts
  front/src/app/components/courses/form-inscr-courses/form-inscr-courses.component.ts
  front/src/app/components/courses/landing-courses/landing-courses.component.ts
  front/src/app/components/header/header.component.html
  front/src/app/components/header/header.component.ts
  front/src/app/core/model/users.model.ts
  front/src/app/lib/primeNG/primeng/primeng.module.ts
  front/src/app/services/users.service.ts
Labels: feature

#27 fix(course-detail): Correct Style
  back/seeders/2023-08-25-course-seed.js
  back/seeders/2023-08-30-courseDetail-seed.js
  front/src/app/components/courses/courses-detail/courses-detail.component.html
Labels: style

#29 fix(seed): Fix the course details seeder
  back/seeders/2023-08-30-courseDetail-seed.js
Labels: bug
